# Generated by Django 2.2 on 2019-06-26 01:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.FloatField(help_text='Valor do pagamento', validators=[django.core.validators.MinValueValidator(limit_value=1), django.core.validators.DecimalValidator(decimal_places=2, max_digits=None)])),
                ('contract', models.ForeignKey(help_text='Contrato do pagamento', on_delete=django.db.models.deletion.CASCADE, to='contracts.Contract')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
