# Generated by Django 2.2.2 on 2019-06-26 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20190626_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(help_text='Contrato do pagamento', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='contracts.Contract'),
        ),
    ]
