# Generated by Django 2.2.2 on 2019-06-26 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190626_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='value',
            field=models.FloatField(help_text='Valor do pagamento', validators=[django.core.validators.MinValueValidator(limit_value=1)]),
        ),
    ]
