# Generated by Django 2.2.2 on 2019-07-07 04:06

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bank', models.TextField(help_text='Banco do contrato')),
                ('amount', models.FloatField(help_text='Valor do contrato', validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('interest_rate', models.FloatField(help_text='Porcentagem de juros', validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=1)])),
                ('submission_date', models.DateField(help_text='Data de submissão')),
                ('ip_address', models.GenericIPAddressField()),
            ],
            options={
                'ordering': ['client_id'],
            },
        ),
    ]
