# Generated by Django 2.2.2 on 2019-06-26 21:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('info', models.TextField(help_text='Informações sobre o contrato')),
                ('initial_value', models.FloatField(help_text='Valor do contrato', validators=[django.core.validators.MinValueValidator(limit_value=1)])),
                ('interest_rate', models.FloatField(help_text='Porcentagem de juros', validators=[django.core.validators.MinValueValidator(limit_value=0), django.core.validators.MaxValueValidator(limit_value=1)])),
                ('start_date', models.DateField()),
                ('user', models.ForeignKey(help_text='Usuário do contrato', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user_id'],
            },
        ),
    ]
