# Generated by Django 2.2 on 2019-06-26 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['user_id']},
        ),
    ]
