# Generated by Django 2.2.2 on 2019-06-26 20:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='user',
            field=models.ForeignKey(help_text='Usuário do contrato', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to=settings.AUTH_USER_MODEL),
        ),
    ]
